// UK subjects taught from Year 1 to Year 13
export const UK_SCHOOL_SUBJECTS = [
  // Core subjects
  "English",
  "Mathematics",
  "Science",
  // Foundation subjects (Primary & Secondary)
  "Art and Design",
  "Citizenship",
  "Computing",
  "Design and Technology",
  "Geography",
  "History",
  "Music",
  "Physical Education",
  "PSHE",
  // Languages
  "French",
  "Spanish",
  "German",
  "Mandarin",
  "Latin",
  // Secondary/GCSE/A-Level subjects
  "Biology",
  "Chemistry",
  "Physics",
  "English Literature",
  "English Language",
  "Religious Education",
  "Business Studies",
  "Economics",
  "Psychology",
  "Sociology",
  "Philosophy",
  "Politics",
  "Law",
  "Media Studies",
  "Film Studies",
  "Drama",
  "Dance",
  "Photography",
  "Graphic Design",
  "Textiles",
  "Food Technology",
  "Health and Social Care",
  "Child Development",
  "Travel and Tourism",
  "Accounting",
  "Statistics",
  "Further Mathematics",
  "Computer Science",
  "ICT",
  "Electronics",
  "Engineering",
  "Product Design",
  "Classical Civilisation",
  "Ancient History",
  "Archaeology",
  "Geology",
  "Astronomy",
  "Environmental Science",
  "Sports Science",
  "Music Technology",
];

// Top 15 tutoring subjects
export const TUTORING_SUBJECTS = [
  "Mathematics",
  "English",
  "Science",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Spanish",
  "French",
  "German",
  "Computer Science",
  "Economics",
  "Music",
  "Art",
];